/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/lib/utils.ts",
      type: "registry:lib",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "haptic": {
    name: "haptic",
    description: "Trigger haptic feedback on mobile devices.",
    type: "registry:lib",
    files: [{
      path: "src/registry/lib/haptic/haptic.ts",
      type: "registry:lib",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/haptic/haptic.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/hooks/use-layout-effect.tsx",
      type: "registry:hook",
      target: "",
    },{
      path: "src/hooks/use-controllable-state.ts",
      type: "registry:hook",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/hooks/use-layout-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-sound": {
    name: "use-sound",
    description: "Custom React hook to load and play a sound from a given URL using the Web Audio API.",
    type: "registry:hook",
    files: [{
      path: "src/hooks/use-sound.ts",
      type: "registry:hook",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/hooks/use-sound.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "theme-switcher": {
    name: "theme-switcher",
    description: "Toggle between system, light, and dark themes in Next.js apps.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/theme-switcher/theme-switcher.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/theme-switcher/theme-switcher.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "text-flip": {
    name: "text-flip",
    description: "Animated text that cycles through items with a smooth flip transition.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/text-flip/text-flip.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/text-flip/text-flip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "apple-hello-effect": {
    name: "apple-hello-effect",
    description: "SVG writing animation inspired by Apple's Hello screen.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/apple-hello-effect/apple-hello-effect.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/apple-hello-effect/apple-hello-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "wheel-picker": {
    name: "wheel-picker",
    description: "iOS-like wheel picker for React with smooth inertia scrolling and infinite loop support.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/wheel-picker/wheel-picker.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/wheel-picker/wheel-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "work-experience": {
    name: "work-experience",
    description: "Display work experiences with role details, company logos, and durations.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/work-experience/work-experience.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/work-experience/work-experience.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "Smooth, light-sweeping shimmer animation for text.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/shimmering-text/shimmering-text.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/shimmering-text/shimmering-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "slide-to-unlock": {
    name: "slide-to-unlock",
    description: "Interactive slider inspired by the classic iPhone 'slide to unlock' gesture.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/slide-to-unlock/slide-to-unlock.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/slide-to-unlock/slide-to-unlock.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "testimonial": {
    name: "testimonial",
    description: "Display user feedback with author info, avatar, and verified badge.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial/testimonial.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial/testimonial.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "github-stars": {
    name: "github-stars",
    description: "Display GitHub repo star count with formatted numbers and full-count tooltip.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/github-stars/github-stars.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/github-stars/github-stars.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "scroll-fade-effect": {
    name: "scroll-fade-effect",
    description: "Fade content edges as you scroll, for both vertical and horizontal layouts.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/scroll-fade-effect/scroll-fade-effect.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/scroll-fade-effect/scroll-fade-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "consent-manager": {
    name: "consent-manager",
    description: "Cookie and tracking consent banner for Next.js, built on c15t.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/consent-manager/consent-manager.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/consent-manager/consent-manager.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "copy-button": {
    name: "copy-button",
    description: "Copy text to clipboard with visual feedback and animation.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/copy-button/copy-button.tsx",
      type: "registry:component",
      target: "",
    },{
      path: "src/hooks/use-copy-to-clipboard.ts",
      type: "registry:hook",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/copy-button/copy-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "code-block-command": {
    name: "code-block-command",
    description: "Display install commands with package manager switcher and copy button.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/code-block-command/code-block-command.tsx",
      type: "registry:component",
      target: "",
    },{
      path: "src/components/base/ui/tabs.tsx",
      type: "registry:component",
      target: "",
    },{
      path: "src/hooks/use-package-manager.ts",
      type: "registry:hook",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/code-block-command/code-block-command.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "login-01": {
    name: "login-01",
    description: "A simple login form.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/login-01/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx",
    },{
      path: "src/registry/blocks/login-01/components/login-form.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/login-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "text-flip-demo": {
    name: "text-flip-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/text-flip-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/text-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "apple-hello-effect-vi-demo": {
    name: "apple-hello-effect-vi-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-vi-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-vi-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "apple-hello-effect-en-demo": {
    name: "apple-hello-effect-en-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-en-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/apple-hello-effect-en-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/theme-switcher-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/wheel-picker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "wheel-picker-form-demo": {
    name: "wheel-picker-form-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/wheel-picker-form-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "work-experience-demo": {
    name: "work-experience-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/work-experience-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "shimmering-text-demo-01": {
    name: "shimmering-text-demo-01",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-01.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/shimmering-text-demo-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "shimmering-text-demo-02": {
    name: "shimmering-text-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/shimmering-text-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/shimmering-text-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "slide-to-unlock-demo-01": {
    name: "slide-to-unlock-demo-01",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-01.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/slide-to-unlock-demo-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "slide-to-unlock-demo-02": {
    name: "slide-to-unlock-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/slide-to-unlock-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "slide-to-unlock-demo-03": {
    name: "slide-to-unlock-demo-03",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/slide-to-unlock-demo-03.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/slide-to-unlock-demo-03.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "testimonial-demo": {
    name: "testimonial-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "testimonials-marquee-demo-01": {
    name: "testimonials-marquee-demo-01",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo-01.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonials-marquee-demo-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "testimonials-marquee-demo-02": {
    name: "testimonials-marquee-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonials-marquee-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonials-marquee-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "github-stars-demo": {
    name: "github-stars-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-stars-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-stars-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "scroll-fade-effect-demo-01": {
    name: "scroll-fade-effect-demo-01",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-01.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "scroll-fade-effect-demo-02": {
    name: "scroll-fade-effect-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-02.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "scroll-fade-effect-demo-03": {
    name: "scroll-fade-effect-demo-03",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-03.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo-03.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "scroll-fade-effect-demo-04": {
    name: "scroll-fade-effect-demo-04",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/scroll-fade-effect-demo-04.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/scroll-fade-effect-demo-04.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "code-block-command-demo": {
    name: "code-block-command-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/code-block-command-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/code-block-command-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "code-block-command-convert-demo": {
    name: "code-block-command-convert-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/code-block-command-convert-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/code-block-command-convert-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/copy-button-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/copy-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "haptic-demo": {
    name: "haptic-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/haptic-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/haptic-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
}